### ISSUE TITLE
Fix CI/CD for dev branch

### ISSUE THREAD

**Issue by qwergram** [project-rakan/rakan#20]

**Comment by kdmcc** [comment]
Added an [action](https://github.com/project-rakan/rakan/blob/python-wrapper/action.yml) to run build the [docker image](https://github.com/project-rakan/rakan/blob/python-wrapper/dockerfile), and an [entrypoint](https://github.com/project-rakan/rakan/blob/python-wrapper/entrypoint.sh) to run `make build` and `make test`, and a [workflow](https://github.com/project-rakan/rakan/blob/python-wrapper/.github/workflows/tests.yml) to make sure that both were successful. We should be able to use this workflow/action for a CI. Currently, the workflow is set to run with every push.

To change it to only run on pushes and pull requests to `dev` and `master`, the file would being with:
```
name: CI

on: 
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
```
[Here is an example of the workflow in action](https://github.com/project-rakan/rakan/runs/691720449?check_suite_focus=true)
If you click on the `Run /./` tab, you'll have to scroll all the way to the bottom of the output because it shows the entire process of the docker build. The useful output will be at the bottom where the `make test` output is located

You will also see that the workflow takes ~4 minutes to complete. We will just have to be patient when pushing code to master!

**Comment by kdmcc** [comment]
Currently, the files for the CI are on the `python-wrapper` branch, and I don't know enough about github to know how to push them to `dev` without pushing my other changes as well. 

For now I will try to finish my work on the wrapper so that this can be merged into `dev` all together. 
> (should I do this?)

**Comment by qwergram** [comment]
Ah, I see what you're doing. I pulled your branch into my branch to see the difference and there appears to be some merge conflicts in the dockerfile. (We have two different entrypoints) Let's meet up and talk about how we want to resolve this
