### ISSUE TITLE
googletest submodule command in wiki

### ISSUE THREAD

**Issue by timotheeandres** [project-rakan/rakan#38]
Two things: first, shouldn't the submodule command be `git submodule add https://github.com/google/googletest.git` instead? Second, since your submodule is already in the .gitmodules file, why not use the command `git submodule upgrade --init`? Even better, you could recommend using the `--recurse-submodules` when cloning, since the front-end already recommends Git >= 2.13.0

**Comment by gooooooooooooooose** [comment]
Thanks for the feedback!

Firstly, you are correct. The command is `git submodule add https://github.com/google/googletest.git`, we will fix that in our wiki. Secondly, we interpreted the documentation assignment prompt in a way such that a developer would start fresh with only the Rakan files, which is why we thought adding the submodule command was necessary. However, with the `.gitsubmodules` file already there, a developer would not need to add the googletest submodule but rather just upgrade. Lastly, the back-end team did not realize the front-end team specified a Git version (our fault in communication). We will take your recommendations into heavy consideration!
